### ISSUE TITLE
images? videos?

### ISSUE THREAD

**Issue by afangg** [mcantow/padm-project#1]
the ones in the repo don't seem to work

**Comment by mcantow** [comment]
What browser are you using? They are working for my partner and I.

**Comment by mcantow** [comment]
If the problem persists the gif for section two is call unoptimized.gif in the main folder of the repo and the gif for section three is called optimized.gif

**Comment by afangg** [comment]
ah it doesn't work in safari including the ones in the main folder. it works on google chrome though thanks
